name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17
        
      - name: Install Dependencies
        run: npm install

      - name: Run Test
        run: npm run test

      - name: Build the app
        if: github.event_name == 'push'
        run: npm run build

      - name: Docker Setup Buildx
        if: github.event_name == 'push'
        uses: docker/setup-buildx-action@v3.0.0

      - name: Docker Login
        if: github.event_name == 'push'
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        if: github.event_name == 'push'
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: autodocker3/twitter-user-service:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
